#!/bin/bash -e
SIREUM_SCRIPT=$(cd -P "$(dirname "$0")" && pwd -P) && SIREUM_SCRIPT=$SIREUM_SCRIPT/$(basename "$0")
while [[ -h $SIREUM_SCRIPT ]]; do DIR=$(dirname "$SIREUM_SCRIPT"); SYM=$(readlink "$SIREUM_SCRIPT"); SIREUM_SCRIPT=$(cd "$DIR" && cd "$(dirname "$SYM")" && pwd)/$(basename "$SYM"); done
export SIREUM_HOME=$(dirname "$SIREUM_SCRIPT")
JAVA_HOME=${SIREUM_HOME}/platform/java
JAVA=${JAVA_HOME}/bin/java
SIREUM_JAR=${SIREUM_HOME}/bin/sireum.jar
DETECT_BUILD=${SIREUM_HOME}/bin/detect-build.sh
if [ -f ${DETECT_BUILD} ]; then
  ${DETECT_BUILD}
fi
: ${JAVA_OPTIONS:=-Xmx1G -XX:+UseG1GC -Xss2m}
: ${JAVA_PROPERTIES:=}
${JAVA} ${JAVA_OPTIONS} ${JAVA_PROPERTIES} -Dfile.encoding=UTF-8 -jar ${SIREUM_JAR} "$@"